#ifndef SYNTH__NOTES_H_
#define SYNTH__NOTES_H_

#include "types.h"

namespace synth {

struct Pitch
{
  uint8_t value;
};

static constexpr voltage_t ToVoltage(const Pitch& pitch)
{
  return static_cast<voltage_t>((static_cast<int32_t>(pitch.value) - 12) * static_cast<int32_t>(millivolts(1000)) / 12);
}


namespace pitch {

static constexpr Pitch Pitch_C0{12};
static constexpr Pitch Pitch_Cs0{13};
static constexpr Pitch Pitch_Dd0{13};
static constexpr Pitch Pitch_D0{14};
static constexpr Pitch Pitch_Ds0{15};
static constexpr Pitch Pitch_Eb0{15};
static constexpr Pitch Pitch_E0{16};
static constexpr Pitch Pitch_F0{17};
static constexpr Pitch Pitch_Fs0{18};
static constexpr Pitch Pitch_Gb0{18};
static constexpr Pitch Pitch_G0{19};
static constexpr Pitch Pitch_Gs0{20};
static constexpr Pitch Pitch_Ab0{20};
static constexpr Pitch Pitch_A0{21};
static constexpr Pitch Pitch_As0{22};
static constexpr Pitch Pitch_Bb0{22};
static constexpr Pitch Pitch_B0{23};
static constexpr Pitch Pitch_C1{24};
static constexpr Pitch Pitch_Cs1{25};
static constexpr Pitch Pitch_Dd1{25};
static constexpr Pitch Pitch_D1{26};
static constexpr Pitch Pitch_Ds1{27};
static constexpr Pitch Pitch_Eb1{27};
static constexpr Pitch Pitch_E1{28};
static constexpr Pitch Pitch_F1{29};
static constexpr Pitch Pitch_Fs1{30};
static constexpr Pitch Pitch_Gb1{30};
static constexpr Pitch Pitch_G1{31};
static constexpr Pitch Pitch_Gs1{32};
static constexpr Pitch Pitch_Ab1{32};
static constexpr Pitch Pitch_A1{33};
static constexpr Pitch Pitch_As1{34};
static constexpr Pitch Pitch_Bb1{34};
static constexpr Pitch Pitch_B1{35};
static constexpr Pitch Pitch_C2{36};
static constexpr Pitch Pitch_Cs2{37};
static constexpr Pitch Pitch_Dd2{37};
static constexpr Pitch Pitch_D2{38};
static constexpr Pitch Pitch_Ds2{39};
static constexpr Pitch Pitch_Eb2{39};
static constexpr Pitch Pitch_E2{40};
static constexpr Pitch Pitch_F2{41};
static constexpr Pitch Pitch_Fs2{42};
static constexpr Pitch Pitch_Gb2{42};
static constexpr Pitch Pitch_G2{43};
static constexpr Pitch Pitch_Gs2{44};
static constexpr Pitch Pitch_Ab2{44};
static constexpr Pitch Pitch_A2{45};
static constexpr Pitch Pitch_As2{46};
static constexpr Pitch Pitch_Bb2{46};
static constexpr Pitch Pitch_B2{47};
static constexpr Pitch Pitch_C3{48};
static constexpr Pitch Pitch_Cs3{49};
static constexpr Pitch Pitch_Dd3{49};
static constexpr Pitch Pitch_D3{50};
static constexpr Pitch Pitch_Ds3{51};
static constexpr Pitch Pitch_Eb3{51};
static constexpr Pitch Pitch_E3{52};
static constexpr Pitch Pitch_F3{53};
static constexpr Pitch Pitch_Fs3{54};
static constexpr Pitch Pitch_Gb3{54};
static constexpr Pitch Pitch_G3{55};
static constexpr Pitch Pitch_Gs3{56};
static constexpr Pitch Pitch_Ab3{56};
static constexpr Pitch Pitch_A3{57};
static constexpr Pitch Pitch_As3{58};
static constexpr Pitch Pitch_Bb3{58};
static constexpr Pitch Pitch_B3{59};
static constexpr Pitch Pitch_C4{60};
static constexpr Pitch Pitch_Cs4{61};
static constexpr Pitch Pitch_Dd4{61};
static constexpr Pitch Pitch_D4{62};
static constexpr Pitch Pitch_Ds4{63};
static constexpr Pitch Pitch_Eb4{63};
static constexpr Pitch Pitch_E4{64};
static constexpr Pitch Pitch_F4{65};
static constexpr Pitch Pitch_Fs4{66};
static constexpr Pitch Pitch_Gb4{66};
static constexpr Pitch Pitch_G4{67};
static constexpr Pitch Pitch_Gs4{68};
static constexpr Pitch Pitch_Ab4{68};
static constexpr Pitch Pitch_A4{69};
static constexpr Pitch Pitch_As4{70};
static constexpr Pitch Pitch_Bb4{70};
static constexpr Pitch Pitch_B4{71};
static constexpr Pitch Pitch_C5{72};
static constexpr Pitch Pitch_Cs5{73};
static constexpr Pitch Pitch_Dd5{73};
static constexpr Pitch Pitch_D5{74};
static constexpr Pitch Pitch_Ds5{75};
static constexpr Pitch Pitch_Eb5{75};
static constexpr Pitch Pitch_E5{76};
static constexpr Pitch Pitch_F5{77};
static constexpr Pitch Pitch_Fs5{78};
static constexpr Pitch Pitch_Gb5{78};
static constexpr Pitch Pitch_G5{79};
static constexpr Pitch Pitch_Gs5{80};
static constexpr Pitch Pitch_Ab5{80};
static constexpr Pitch Pitch_A5{81};
static constexpr Pitch Pitch_As5{82};
static constexpr Pitch Pitch_Bb5{82};
static constexpr Pitch Pitch_B5{83};
static constexpr Pitch Pitch_C6{84};
static constexpr Pitch Pitch_Cs6{85};
static constexpr Pitch Pitch_Dd6{85};
static constexpr Pitch Pitch_D6{86};
static constexpr Pitch Pitch_Ds6{87};
static constexpr Pitch Pitch_Eb6{87};
static constexpr Pitch Pitch_E6{88};
static constexpr Pitch Pitch_F6{89};
static constexpr Pitch Pitch_Fs6{90};
static constexpr Pitch Pitch_Gb6{90};
static constexpr Pitch Pitch_G6{91};
static constexpr Pitch Pitch_Gs6{92};
static constexpr Pitch Pitch_Ab6{92};
static constexpr Pitch Pitch_A6{93};
static constexpr Pitch Pitch_As6{94};
static constexpr Pitch Pitch_Bb6{94};
static constexpr Pitch Pitch_B6{95};
static constexpr Pitch Pitch_C7{96};
static constexpr Pitch Pitch_Cs7{97};
static constexpr Pitch Pitch_Dd7{97};
static constexpr Pitch Pitch_D7{98};
static constexpr Pitch Pitch_Ds7{99};
static constexpr Pitch Pitch_Eb7{99};
static constexpr Pitch Pitch_E7{100};
static constexpr Pitch Pitch_F7{101};
static constexpr Pitch Pitch_Fs7{102};
static constexpr Pitch Pitch_Gb7{102};
static constexpr Pitch Pitch_G7{103};
static constexpr Pitch Pitch_Gs7{104};
static constexpr Pitch Pitch_Ab7{104};
static constexpr Pitch Pitch_A7{105};
static constexpr Pitch Pitch_As7{106};
static constexpr Pitch Pitch_Bb7{106};
static constexpr Pitch Pitch_B7{107};
static constexpr Pitch Pitch_C8{108};
static constexpr Pitch Pitch_Cs8{109};
static constexpr Pitch Pitch_Dd8{109};
static constexpr Pitch Pitch_D8{110};
static constexpr Pitch Pitch_Ds8{111};
static constexpr Pitch Pitch_Eb8{111};
static constexpr Pitch Pitch_E8{112};
static constexpr Pitch Pitch_F8{113};
static constexpr Pitch Pitch_Fs8{114};
static constexpr Pitch Pitch_Gb8{114};
static constexpr Pitch Pitch_G8{115};
static constexpr Pitch Pitch_Gs8{116};
static constexpr Pitch Pitch_Ab8{116};
static constexpr Pitch Pitch_A8{117};
static constexpr Pitch Pitch_As8{118};
static constexpr Pitch Pitch_Bb8{118};
static constexpr Pitch Pitch_B8{119};
static constexpr Pitch Pitch_C9{120};
static constexpr Pitch Pitch_Cs9{121};
static constexpr Pitch Pitch_Dd9{121};
static constexpr Pitch Pitch_D9{122};
static constexpr Pitch Pitch_Ds9{123};
static constexpr Pitch Pitch_Eb9{123};
static constexpr Pitch Pitch_E9{124};
static constexpr Pitch Pitch_F9{125};
static constexpr Pitch Pitch_Fs9{126};
static constexpr Pitch Pitch_Gb9{126};
static constexpr Pitch Pitch_G9{127};





namespace midi {
static const uint8_t Pitch_C0 = 12;
static const uint8_t Pitch_Cs0 = 13;
static const uint8_t Pitch_Dd0 = 13;
static const uint8_t Pitch_D0 = 14;
static const uint8_t Pitch_Ds0 = 15;
static const uint8_t Pitch_Eb0 = 15;
static const uint8_t Pitch_E0 = 16;
static const uint8_t Pitch_F0 = 17;
static const uint8_t Pitch_Fs0 = 18;
static const uint8_t Pitch_Gb0 = 18;
static const uint8_t Pitch_G0 = 19;
static const uint8_t Pitch_Gs0 = 20;
static const uint8_t Pitch_Ab0 = 20;
static const uint8_t Pitch_A0 = 21;
static const uint8_t Pitch_As0 = 22;
static const uint8_t Pitch_Bb0 = 22;
static const uint8_t Pitch_B0 = 23;
static const uint8_t Pitch_C1 = 24;
static const uint8_t Pitch_Cs1 = 25;
static const uint8_t Pitch_Dd1 = 25;
static const uint8_t Pitch_D1 = 26;
static const uint8_t Pitch_Ds1 = 27;
static const uint8_t Pitch_Eb1 = 27;
static const uint8_t Pitch_E1 = 28;
static const uint8_t Pitch_F1 = 29;
static const uint8_t Pitch_Fs1 = 30;
static const uint8_t Pitch_Gb1 = 30;
static const uint8_t Pitch_G1 = 31;
static const uint8_t Pitch_Gs1 = 32;
static const uint8_t Pitch_Ab1 = 32;
static const uint8_t Pitch_A1 = 33;
static const uint8_t Pitch_As1 = 34;
static const uint8_t Pitch_Bb1 = 34;
static const uint8_t Pitch_B1 = 35;
static const uint8_t Pitch_C2 = 36;
static const uint8_t Pitch_Cs2 = 37;
static const uint8_t Pitch_Dd2 = 37;
static const uint8_t Pitch_D2 = 38;
static const uint8_t Pitch_Ds2 = 39;
static const uint8_t Pitch_Eb2 = 39;
static const uint8_t Pitch_E2 = 40;
static const uint8_t Pitch_F2 = 41;
static const uint8_t Pitch_Fs2 = 42;
static const uint8_t Pitch_Gb2 = 42;
static const uint8_t Pitch_G2 = 43;
static const uint8_t Pitch_Gs2 = 44;
static const uint8_t Pitch_Ab2 = 44;
static const uint8_t Pitch_A2 = 45;
static const uint8_t Pitch_As2 = 46;
static const uint8_t Pitch_Bb2 = 46;
static const uint8_t Pitch_B2 = 47;
static const uint8_t Pitch_C3 = 48;
static const uint8_t Pitch_Cs3 = 49;
static const uint8_t Pitch_Dd3 = 49;
static const uint8_t Pitch_D3 = 50;
static const uint8_t Pitch_Ds3 = 51;
static const uint8_t Pitch_Eb3 = 51;
static const uint8_t Pitch_E3 = 52;
static const uint8_t Pitch_F3 = 53;
static const uint8_t Pitch_Fs3 = 54;
static const uint8_t Pitch_Gb3 = 54;
static const uint8_t Pitch_G3 = 55;
static const uint8_t Pitch_Gs3 = 56;
static const uint8_t Pitch_Ab3 = 56;
static const uint8_t Pitch_A3 = 57;
static const uint8_t Pitch_As3 = 58;
static const uint8_t Pitch_Bb3 = 58;
static const uint8_t Pitch_B3 = 59;
static const uint8_t Pitch_C4 = 60;
static const uint8_t Pitch_Cs4 = 61;
static const uint8_t Pitch_Dd4 = 61;
static const uint8_t Pitch_D4 = 62;
static const uint8_t Pitch_Ds4 = 63;
static const uint8_t Pitch_Eb4 = 63;
static const uint8_t Pitch_E4 = 64;
static const uint8_t Pitch_F4 = 65;
static const uint8_t Pitch_Fs4 = 66;
static const uint8_t Pitch_Gb4 = 66;
static const uint8_t Pitch_G4 = 67;
static const uint8_t Pitch_Gs4 = 68;
static const uint8_t Pitch_Ab4 = 68;
static const uint8_t Pitch_A4 = 69;
static const uint8_t Pitch_As4 = 70;
static const uint8_t Pitch_Bb4 = 70;
static const uint8_t Pitch_B4 = 71;
static const uint8_t Pitch_C5 = 72;
static const uint8_t Pitch_Cs5 = 73;
static const uint8_t Pitch_Dd5 = 73;
static const uint8_t Pitch_D5 = 74;
static const uint8_t Pitch_Ds5 = 75;
static const uint8_t Pitch_Eb5 = 75;
static const uint8_t Pitch_E5 = 76;
static const uint8_t Pitch_F5 = 77;
static const uint8_t Pitch_Fs5 = 78;
static const uint8_t Pitch_Gb5 = 78;
static const uint8_t Pitch_G5 = 79;
static const uint8_t Pitch_Gs5 = 80;
static const uint8_t Pitch_Ab5 = 80;
static const uint8_t Pitch_A5 = 81;
static const uint8_t Pitch_As5 = 82;
static const uint8_t Pitch_Bb5 = 82;
static const uint8_t Pitch_B5 = 83;
static const uint8_t Pitch_C6 = 84;
static const uint8_t Pitch_Cs6 = 85;
static const uint8_t Pitch_Dd6 = 85;
static const uint8_t Pitch_D6 = 86;
static const uint8_t Pitch_Ds6 = 87;
static const uint8_t Pitch_Eb6 = 87;
static const uint8_t Pitch_E6 = 88;
static const uint8_t Pitch_F6 = 89;
static const uint8_t Pitch_Fs6 = 90;
static const uint8_t Pitch_Gb6 = 90;
static const uint8_t Pitch_G6 = 91;
static const uint8_t Pitch_Gs6 = 92;
static const uint8_t Pitch_Ab6 = 92;
static const uint8_t Pitch_A6 = 93;
static const uint8_t Pitch_As6 = 94;
static const uint8_t Pitch_Bb6 = 94;
static const uint8_t Pitch_B6 = 95;
static const uint8_t Pitch_C7 = 96;
static const uint8_t Pitch_Cs7 = 97;
static const uint8_t Pitch_Dd7 = 97;
static const uint8_t Pitch_D7 = 98;
static const uint8_t Pitch_Ds7 = 99;
static const uint8_t Pitch_Eb7 = 99;
static const uint8_t Pitch_E7 = 100;
static const uint8_t Pitch_F7 = 101;
static const uint8_t Pitch_Fs7 = 102;
static const uint8_t Pitch_Gb7 = 102;
static const uint8_t Pitch_G7 = 103;
static const uint8_t Pitch_Gs7 = 104;
static const uint8_t Pitch_Ab7 = 104;
static const uint8_t Pitch_A7 = 105;
static const uint8_t Pitch_As7 = 106;
static const uint8_t Pitch_Bb7 = 106;
static const uint8_t Pitch_B7 = 107;
static const uint8_t Pitch_C8 = 108;
static const uint8_t Pitch_Cs8 = 109;
static const uint8_t Pitch_Dd8 = 109;
static const uint8_t Pitch_D8 = 110;
static const uint8_t Pitch_Ds8 = 111;
static const uint8_t Pitch_Eb8 = 111;
static const uint8_t Pitch_E8 = 112;
static const uint8_t Pitch_F8 = 113;
static const uint8_t Pitch_Fs8 = 114;
static const uint8_t Pitch_Gb8 = 114;
static const uint8_t Pitch_G8 = 115;
static const uint8_t Pitch_Gs8 = 116;
static const uint8_t Pitch_Ab8 = 116;
static const uint8_t Pitch_A8 = 117;
static const uint8_t Pitch_As8 = 118;
static const uint8_t Pitch_Bb8 = 118;
static const uint8_t Pitch_B8 = 119;
static const uint8_t Pitch_C9 = 120;
static const uint8_t Pitch_Cs9 = 121;
static const uint8_t Pitch_Dd9 = 121;
static const uint8_t Pitch_D9 = 122;
static const uint8_t Pitch_Ds9 = 123;
static const uint8_t Pitch_Eb9 = 123;
static const uint8_t Pitch_E9 = 124;
static const uint8_t Pitch_F9 = 125;
static const uint8_t Pitch_Fs9 = 126;
static const uint8_t Pitch_Gb9 = 126;
static const uint8_t Pitch_G9 = 127;
} // namespace midi

namespace voltage {
static const voltage_t Pitch_C0 = millivolts(0);
static const voltage_t Pitch_Cs0 = millivolts(83);
static const voltage_t Pitch_Dd0 = millivolts(83);
static const voltage_t Pitch_D0 = millivolts(166);
static const voltage_t Pitch_Ds0 = millivolts(250);
static const voltage_t Pitch_Eb0 = millivolts(250);
static const voltage_t Pitch_E0 = millivolts(333);
static const voltage_t Pitch_F0 = millivolts(416);
static const voltage_t Pitch_Fs0 = millivolts(500);
static const voltage_t Pitch_Gb0 = millivolts(500);
static const voltage_t Pitch_G0 = millivolts(583);
static const voltage_t Pitch_Gs0 = millivolts(666);
static const voltage_t Pitch_Ab0 = millivolts(666);
static const voltage_t Pitch_A0 = millivolts(750);
static const voltage_t Pitch_As0 = millivolts(833);
static const voltage_t Pitch_Bb0 = millivolts(833);
static const voltage_t Pitch_B0 = millivolts(916);
static const voltage_t Pitch_C1 = millivolts(1000);
static const voltage_t Pitch_Cs1 = millivolts(1083);
static const voltage_t Pitch_Dd1 = millivolts(1083);
static const voltage_t Pitch_D1 = millivolts(1166);
static const voltage_t Pitch_Ds1 = millivolts(1250);
static const voltage_t Pitch_Eb1 = millivolts(1250);
static const voltage_t Pitch_E1 = millivolts(1333);
static const voltage_t Pitch_F1 = millivolts(1416);
static const voltage_t Pitch_Fs1 = millivolts(1500);
static const voltage_t Pitch_Gb1 = millivolts(1500);
static const voltage_t Pitch_G1 = millivolts(1583);
static const voltage_t Pitch_Gs1 = millivolts(1666);
static const voltage_t Pitch_Ab1 = millivolts(1666);
static const voltage_t Pitch_A1 = millivolts(1750);
static const voltage_t Pitch_As1 = millivolts(1833);
static const voltage_t Pitch_Bb1 = millivolts(1833);
static const voltage_t Pitch_B1 = millivolts(1916);
static const voltage_t Pitch_C2 = millivolts(2000);
static const voltage_t Pitch_Cs2 = millivolts(2083);
static const voltage_t Pitch_Dd2 = millivolts(2083);
static const voltage_t Pitch_D2 = millivolts(2166);
static const voltage_t Pitch_Ds2 = millivolts(2250);
static const voltage_t Pitch_Eb2 = millivolts(2250);
static const voltage_t Pitch_E2 = millivolts(2333);
static const voltage_t Pitch_F2 = millivolts(2416);
static const voltage_t Pitch_Fs2 = millivolts(2500);
static const voltage_t Pitch_Gb2 = millivolts(2500);
static const voltage_t Pitch_G2 = millivolts(2583);
static const voltage_t Pitch_Gs2 = millivolts(2666);
static const voltage_t Pitch_Ab2 = millivolts(2666);
static const voltage_t Pitch_A2 = millivolts(2750);
static const voltage_t Pitch_As2 = millivolts(2833);
static const voltage_t Pitch_Bb2 = millivolts(2833);
static const voltage_t Pitch_B2 = millivolts(2916);
static const voltage_t Pitch_C3 = millivolts(3000);
static const voltage_t Pitch_Cs3 = millivolts(3083);
static const voltage_t Pitch_Dd3 = millivolts(3083);
static const voltage_t Pitch_D3 = millivolts(3166);
static const voltage_t Pitch_Ds3 = millivolts(3250);
static const voltage_t Pitch_Eb3 = millivolts(3250);
static const voltage_t Pitch_E3 = millivolts(3333);
static const voltage_t Pitch_F3 = millivolts(3416);
static const voltage_t Pitch_Fs3 = millivolts(3500);
static const voltage_t Pitch_Gb3 = millivolts(3500);
static const voltage_t Pitch_G3 = millivolts(3583);
static const voltage_t Pitch_Gs3 = millivolts(3666);
static const voltage_t Pitch_Ab3 = millivolts(3666);
static const voltage_t Pitch_A3 = millivolts(3750);
static const voltage_t Pitch_As3 = millivolts(3833);
static const voltage_t Pitch_Bb3 = millivolts(3833);
static const voltage_t Pitch_B3 = millivolts(3916);
static const voltage_t Pitch_C4 = millivolts(4000);
static const voltage_t Pitch_Cs4 = millivolts(4083);
static const voltage_t Pitch_Dd4 = millivolts(4083);
static const voltage_t Pitch_D4 = millivolts(4166);
static const voltage_t Pitch_Ds4 = millivolts(4250);
static const voltage_t Pitch_Eb4 = millivolts(4250);
static const voltage_t Pitch_E4 = millivolts(4333);
static const voltage_t Pitch_F4 = millivolts(4416);
static const voltage_t Pitch_Fs4 = millivolts(4500);
static const voltage_t Pitch_Gb4 = millivolts(4500);
static const voltage_t Pitch_G4 = millivolts(4583);
static const voltage_t Pitch_Gs4 = millivolts(4666);
static const voltage_t Pitch_Ab4 = millivolts(4666);
static const voltage_t Pitch_A4 = millivolts(4750);
static const voltage_t Pitch_As4 = millivolts(4833);
static const voltage_t Pitch_Bb4 = millivolts(4833);
static const voltage_t Pitch_B4 = millivolts(4916);
static const voltage_t Pitch_C5 = millivolts(5000);
static const voltage_t Pitch_Cs5 = millivolts(5083);
static const voltage_t Pitch_Dd5 = millivolts(5083);
static const voltage_t Pitch_D5 = millivolts(5166);
static const voltage_t Pitch_Ds5 = millivolts(5250);
static const voltage_t Pitch_Eb5 = millivolts(5250);
static const voltage_t Pitch_E5 = millivolts(5333);
static const voltage_t Pitch_F5 = millivolts(5416);
static const voltage_t Pitch_Fs5 = millivolts(5500);
static const voltage_t Pitch_Gb5 = millivolts(5500);
static const voltage_t Pitch_G5 = millivolts(5583);
static const voltage_t Pitch_Gs5 = millivolts(5666);
static const voltage_t Pitch_Ab5 = millivolts(5666);
static const voltage_t Pitch_A5 = millivolts(5750);
static const voltage_t Pitch_As5 = millivolts(5833);
static const voltage_t Pitch_Bb5 = millivolts(5833);
static const voltage_t Pitch_B5 = millivolts(5916);
static const voltage_t Pitch_C6 = millivolts(6000);
static const voltage_t Pitch_Cs6 = millivolts(6083);
static const voltage_t Pitch_Dd6 = millivolts(6083);
static const voltage_t Pitch_D6 = millivolts(6166);
static const voltage_t Pitch_Ds6 = millivolts(6250);
static const voltage_t Pitch_Eb6 = millivolts(6250);
static const voltage_t Pitch_E6 = millivolts(6333);
static const voltage_t Pitch_F6 = millivolts(6416);
static const voltage_t Pitch_Fs6 = millivolts(6500);
static const voltage_t Pitch_Gb6 = millivolts(6500);
static const voltage_t Pitch_G6 = millivolts(6583);
static const voltage_t Pitch_Gs6 = millivolts(6666);
static const voltage_t Pitch_Ab6 = millivolts(6666);
static const voltage_t Pitch_A6 = millivolts(6750);
static const voltage_t Pitch_As6 = millivolts(6833);
static const voltage_t Pitch_Bb6 = millivolts(6833);
static const voltage_t Pitch_B6 = millivolts(6916);
static const voltage_t Pitch_C7 = millivolts(7000);
static const voltage_t Pitch_Cs7 = millivolts(7083);
static const voltage_t Pitch_Dd7 = millivolts(7083);
static const voltage_t Pitch_D7 = millivolts(7166);
static const voltage_t Pitch_Ds7 = millivolts(7250);
static const voltage_t Pitch_Eb7 = millivolts(7250);
static const voltage_t Pitch_E7 = millivolts(7333);
static const voltage_t Pitch_F7 = millivolts(7416);
static const voltage_t Pitch_Fs7 = millivolts(7500);
static const voltage_t Pitch_Gb7 = millivolts(7500);
static const voltage_t Pitch_G7 = millivolts(7583);
static const voltage_t Pitch_Gs7 = millivolts(7666);
static const voltage_t Pitch_Ab7 = millivolts(7666);
static const voltage_t Pitch_A7 = millivolts(7750);
static const voltage_t Pitch_As7 = millivolts(7833);
static const voltage_t Pitch_Bb7 = millivolts(7833);
static const voltage_t Pitch_B7 = millivolts(7916);
static const voltage_t Pitch_C8 = millivolts(8000);
static const voltage_t Pitch_Cs8 = millivolts(8083);
static const voltage_t Pitch_Dd8 = millivolts(8083);
static const voltage_t Pitch_D8 = millivolts(8166);
static const voltage_t Pitch_Ds8 = millivolts(8250);
static const voltage_t Pitch_Eb8 = millivolts(8250);
static const voltage_t Pitch_E8 = millivolts(8333);
static const voltage_t Pitch_F8 = millivolts(8416);
static const voltage_t Pitch_Fs8 = millivolts(8500);
static const voltage_t Pitch_Gb8 = millivolts(8500);
static const voltage_t Pitch_G8 = millivolts(8583);
static const voltage_t Pitch_Gs8 = millivolts(8666);
static const voltage_t Pitch_Ab8 = millivolts(8666);
static const voltage_t Pitch_A8 = millivolts(8750);
static const voltage_t Pitch_As8 = millivolts(8833);
static const voltage_t Pitch_Bb8 = millivolts(8833);
static const voltage_t Pitch_B8 = millivolts(8916);
static const voltage_t Pitch_C9 = millivolts(9000);
static const voltage_t Pitch_Cs9 = millivolts(9083);
static const voltage_t Pitch_Dd9 = millivolts(9083);
static const voltage_t Pitch_D9 = millivolts(9166);
static const voltage_t Pitch_Ds9 = millivolts(9250);
static const voltage_t Pitch_Eb9 = millivolts(9250);
static const voltage_t Pitch_E9 = millivolts(9333);
static const voltage_t Pitch_F9 = millivolts(9416);
static const voltage_t Pitch_Fs9 = millivolts(9500);
static const voltage_t Pitch_Gb9 = millivolts(9500);
static const voltage_t Pitch_G9 = millivolts(9583);
} // namespace voltage

} // namespace pitch
} // namespace synth
#endif // SYNTH__NOTES_H_
